#########
# Video #
#########

# vo=gpu-next — это «движок» рендеринга нового поколения внутри mpv.
vo=gpu-next
# Vulkan Linux, Windows (preferred)
gpu-api=vulkan
gpu-context=auto
# Аппаратное декодирование (HWDEC) (Экономия памяти / Direct Rendering)
vd-lavc-dr=yes
hwdec=auto-safe
# Включаем temporal-dither (на Linux нужно явно указать) (Обман зрения для плавных цветов)
temporal-dither=yes

##########
# Player #
##########

# Включает IPC-сокет для связи с внешними программами (сейчас нужен для Mpv Subs Popout)
input-ipc-server=/tmp/mpvsock
# Сохранять место, громкость, аудиодорожку и субтитры при выходе
save-position-on-quit=yes
watch-later-options=start,volume,mute,aid,sid,secondary-sid,sub-delay
# Не закрывать плеер после окончания видео
keep-open=yes
# Ограничить размер окна при запуске (ограничение на не более чем в процентах от экрана)
autofit-larger=85%x85%
# Наводим порядок в кэше
watch-later-dir="~~/cache/watch_later"
gpu-shader-cache-dir="~~/cache/shaders_cache"

########
# Subs #
########

# Приоритет субтитров
slang=eng,en,en-US,rus,ru
# Пути для поиска субтитров (через запятую или двоеточие)
sub-file-paths=sub:subs:Sub:Subs:subtitles:Subtitles
# подгружать субтитры с похожим, но не точно совпадающим именем файла)
sub-auto=fuzzy

#########
# Audio #
#########

# При первом открытии видео устанавливать определённую громкость
volume=100
# Разрешает увеличивать громкость до 150% (вместо стандартных 130%)
volume-max=150

###############
# Screenshots #
###############

# Путь к папке для сохранения скриншотов
screenshot-directory="~/Pictures/MPV screenshots"
# Шаблон имени файла: Название - Дата - Время
screenshot-template="%F - [%wh. %wM. %wS] (%td.%tm.%tY %tH.%tM.%tS)"
# Формат (png лучше качеством, jpg меньше весит)
screenshot-format=png

##################
# uosc UI plugin #
##################

# uosc provides seeking & volume indicators (via flash-timeline and flash-volume commands)
# if you decide to use them, you don't need osd-bar
osd-bar=no
# uosc will draw its own window controls and border if you disable window border
# border=no

############
# Profiles #
############

# Профиль для конкретной папки с аниме
[anime-folder]
profile-cond=string.match(path, "/home/akulinker/AllMedia/Anime/") ~= nil
alang=jpn,jp,eng,en,rus,ru

# Профиль для другой коллекции
[movies-folder]
profile-cond=string.match(path, "/home/akulinker/AllMedia/Films/") ~= nil or string.match(path, "/home/akulinker/AllMedia/Serials/") ~= nil
alang=eng,en,en-US,jpn,jp,rus,ru
